url: https://ssp4all.github.io
baseurl: 

# Site settings
title: Suraj Pawar
email: spawar2@ncsu.edu
description: "Suraj Pawar is a Gradute student pursuing Master's in Computer Science NC State University, USA. He is interested in Software Engineering and Data Science. 
			This site displays Suraj's projects and prior Software Engineering related experiences."

# Team names, titles and social links
people:
- name: Suraj Pawar
  pic: 4
  position: Critical Thinker
  social:
    - title: twitter
      url: https://twitter.com/ssp4all
    - title: facebook
      url: https://www.facebook.com/SSP4ALL/
    - title: stack-overflow
      url: https://stackoverflow.com/users/9543314/ssp4all


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ssp4all
  - title: facebook
    url: https://www.facebook.com/SSP4ALL/
  - title: stack-overflow
    url: https://stackoverflow.com/users/9543314/ssp4all
  - title: linkedin 
    url: https://www.linkedin.com/in/ssp4all/
  - title: github
    url: http://github.com/ssp4all

# Postal address (add as many lines as necessary)
address:
  - line: USA

# Build settings
markdown: kramdown
permalink: pretty